CREATE TABLE CUSTOMER_INFO (
CUST_ID		VARCHAR(15) NOT NULL PRIMARY KEY,
CUST_FNAME	VARCHAR(25) NOT NULL,
CUST_LNAME	VARCHAR(45) NOT NULL,
CUST_EMAIL	VARCHAR(45),
CUST_GENDER	VARCHAR(1) NOT NULL DEFAULT 'M',
CUST_CREATED	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP

); 


INSERT INTO CUSTOMER_INFO (CUST_ID, CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_GENDER) VALUES 
('9663175755', 'VIJENDRA', 'LAKSHMANA RAO', 'M1031960@MINDTREE.COM', 'M'),
('9741657696', 'AMIT', 'LELE', 'AMIT.LELE@MINDTREE.COM','M'),
('6475394765', 'MIKE', 'SUN', 'MIKE.SUN@MINDTREE.COM', 'M');

COMMIT;



CREATE TABLE RESERVATION_INFO (
  RESERVATION_CONF_NO INT NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  CHECKIN_DATETIME DATETIME NOT NULL,
  CHECKOUT_DATETIME DATETIME NOT NULL,
  CUSTOMER_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (RESERVATION_CONF_NO));
  
  
  CREATE TABLE PMS_RESERVATION_INFO (
  RESERVATION_CONF_NO INT NOT NULL,
  ROOM_NUMBER VARCHAR(45) NOT NULL,
  PROPERTY_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (RESERVATION_CONF_NO));
  
  
  CREATE TABLE PROPERTY_INFO (
  PROPERTY_ID INT NOT NULL,
  PROPERTY_CODE VARCHAR(45) NOT NULL,
  PROPERTY_NAME VARCHAR(45) NOT NULL,
  PROPERTY_GEO_COORDINATES VARCHAR(45) NOT NULL,
  PRIMARY KEY (PROPERTY_ID));

  
  CREATE TABLE DEPARTMENT_ACTION (
  DEPARTMENT_CODE VARCHAR(45) NOT NULL,
  ACTION_CODE VARCHAR(45) NOT NULL,
  PRIMARY KEY (DEPARTMENT_CODE, ACTION_CODE));
  
  
  CREATE TABLE PROPERTY_AMENITIES (
  AMENITY_ID INT NOT NULL,
  PROPERTY_ID INT NOT NULL,
  AMENITY_NAME VARCHAR(45) NOT NULL,
  OPERATING_DAYS VARCHAR(45) NOT NULL,
  OPEN_TIME TIME NOT NULL,
  CLOSING_TIME TIME NOT NULL,
  PRIMARY KEY (AMENITY_ID));

  
  CREATE TABLE CONSUMPTION_INFO (
  CONSUMPTION_ID INT NOT NULL,
  RESERVATION_CONF_NO VARCHAR(45) NOT NULL,
  CONSUMPTION_DATE DATE NOT NULL,
  CONSUMPTION_AMOUNT DOUBLE NOT NULL,
  PRIMARY KEY (CONSUMPTION_ID));

  
  CREATE TABLE SERVICE_REQUEST (
  SERVICE_REQUEST_ID VARCHAR(45) NOT NULL,
  CUSTOMER_ID VARCHAR(45) NOT NULL,
  PROPERTY_ID INT NOT NULL,
  ROOM_NO VARCHAR(45) NOT NULL,
  DEPARTMENT_ID VARCHAR(45) NOT NULL,
  REQUEST_DESC VARCHAR(200) NOT NULL,
  REQUEST_STATUS VARCHAR(45) NOT NULL,
  EXECUTION_TIME DATETIME NULL,
  PRIMARY KEY (SERVICE_REQUEST_ID));
  
  CREATE TABLE CUSTOMER_DEVICE_INFO (
  DEVICE_ID VARCHAR(45) NOT NULL,
  CUSTOMER_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (DEVICE_ID));
  
  