CREATE TABLE CUSTOMER_INFO (
CUST_ID		VARCHAR(15) NOT NULL PRIMARY KEY,
CUST_FNAME	VARCHAR(25) NOT NULL,
CUST_LNAME	VARCHAR(45) NOT NULL,
CUST_EMAIL	VARCHAR(45),
CUST_GENDER	VARCHAR(1) NOT NULL DEFAULT 'M',
CUST_CREATED	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP

); 


INSERT INTO CUSTOMER_INFO (CUST_ID, CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_GENDER) VALUES 
('9663175755', 'VIJENDRA', 'LAKSHMANA RAO', 'M1031960@MINDTREE.COM', 'M'),
('9741657696', 'AMIT', 'LELE', 'AMIT.LELE@MINDTREE.COM','M'),
('6475394765', 'MIKE', 'SUN', 'MIKE.SUN@MINDTREE.COM', 'M');

COMMIT;